version: '3'

services:
  nginx:
    image: nginx:1.14.0
    volumes:
      - ./src:/www
      - ./docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/etc/nginx/inc.d:/etc/nginx/inc.d
    ports:
      - 80:80
    environment:
      SERVER_ADDR: 'auction.local'
      UPSTREAM_ADDR: 'php'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/main.conf.template > /etc/nginx/conf.d/main.conf && exec nginx -g 'daemon off;'"
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/fpm/Dockerfile
    volumes:
      - /Users/sergeytismenko/www/iq-auction:/www:rw
    working_dir: /www/
    environment:
      DATABASE_DSN: 'pgsql:host=postgres;port=5432;dbname=tesmo'
      DATABASE_USER: 'tesmo'
      DATABASE_PASSWROD: 'tesmo'
    links:
      - postgres
      - mysql
      - redis
  postgres:
    image: postgres:10.5
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: 'project'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
  mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_DATABASE: project
        MYSQL_ROOT_PASSWORD: password
      ports:
        - 15306:3306
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes